repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: ["--allow-multiple-documents"]
        exclude: ^charts/.*/templates/.*\.ya?ml$
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: detect-private-key

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.38.0
    hooks:
      - id: yamllint
        args: ["-d", "{extends: default, rules: {line-length: disable}}"]
        exclude: ^charts/.*/templates/.*\.ya?ml$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.7
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format

  - repo: https://github.com/pypa/pip-audit
    rev: v2.10.0
    hooks:
      - id: pip-audit
        name: pip-audit runtime requirements
        args: ["-r", "runtime/requirements.txt"]
        pass_filenames: false
      - id: pip-audit
        name: pip-audit simulator requirements
        args: ["-r", "simulators/requirements.txt"]
        pass_filenames: false

  - repo: local
    hooks:
      - id: checkov-helm-chart
        name: checkov Helm chart
        entry: checkov -d charts/edgepulse-runtime --framework helm --skip-check CKV_K8S_21,CKV_K8S_15,CKV_K8S_43 --soft-fail --quiet
        language: python
        additional_dependencies:
          - checkov==3.2.530
        pass_filenames: false
        always_run: true

      - id: checkov-dockerfile
        name: checkov Dockerfile
        entry: checkov -f runtime/Dockerfile --framework dockerfile --soft-fail --quiet
        language: python
        additional_dependencies:
          - checkov==3.2.530
        pass_filenames: false
        always_run: true
