apiVersion: v1
kind: Service
metadata:
  name: {{ include "edgepulse-runtime.fullname" . }}
  labels:
    {{- include "edgepulse-runtime.labels" . | nindent 4 }}
    app.kubernetes.io/component: runtime
spec:
  type: {{ .Values.runtime.service.type }}
  ports:
    - name: http
      port: {{ .Values.runtime.service.port }}
      targetPort: http
  selector:
    {{- include "edgepulse-runtime.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: runtime
