{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "edgepulse-runtime.serviceAccountName" . }}
  labels:
    {{- include "edgepulse-runtime.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
